### ISSUE TITLE
0.14 Doc Update 

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar-framework.org#107]
For those great contributors helping with the docs, here is what to do, written by Razvan. Please note which section you will be working on in the comments below and I'll update the task list. Thanks!

Scott

Step 1. Investigating what a component can do
-> clone Quasar repo, "quasar dev" -> a browser window will appear with a list of all components. Click on the one of interest
-> see the examples, check source code; also check source code for Quasar component itself (see props, methods and look for events (search '$emit')

Step 2. Documenting the component
-> fork fork https://github.com/smolinari/quasar-framework.org
-> work on dev branch
-> npm install, npm i -g hexo-cli, hexo serve (-> opens up the docs on a local server)
-> add an entry for the new component (if necessary) in /source/_data/pageMenu.yml
-> then create a new *.md file for the component. example: /source/components/alert.md
-> follow other pages as a guideline on how to write doc for a component. try to be consistent

Now, the components that need documentation:
- [x] Alert
- [x] Button
- [x] Chip
- [x] Icon
- [x] InnerLoading
- [x] Modal -> layout example update
- [x] Observables
- [x] Stepper
- [x] Spinner -> dev page broken, so look at Quasar repo source code
- [x] Transition
- [x] Uploader
- [x] Autocomplete
- [x] Button Update #2 (new props and functionality)
- [x] FAB update
- [x] Add "no-uppercase" boolean prop to q-btn
- [x] Chips (not the new Chip) needs a small update on props/methods/events
- [x] Tabs
- [x] Fixed Position
- [x] Dialog changes (needs examples in /dev)
- [x] Chip (update 2 needs color prop and more examples)
- [x] Update color and track-color props for knob 
- [x] Option Group (check Checkbox, Radio, Toggle dev pages for examples)
- [x] List
- [x] Checkbox
- [x] Toggle
- [x] Radio
- [x] Progress (needs clarification from Razvan about what is new.)
- [x] Check to see if .md partials are possible in Hexo
- [x] Cards (as new component)
- [x] Scroll Area
- [x] Input (don't forget "common form component props")
- [x] Range and Double Range
- [x] Search needs an update
- [ ] Item (for lists)
- [ ] Select needs an update
- [ ] Check all form components again
- [ ] Slide Transition
- [ ] Field
- [ ] Layout
- [ ] Add a "View Component Source Code" link to the bottom of the component pages.
- [ ] Add the new prop display-value in the QSelect and QDialogSelect docs

Do what you can. Start with the easier ones for you. I don't expect a perfect job, but best that you can do.

Thanks a lot for your help! Updating docs is essential to releasing v0.14 quicker.

-Razvan

PS from Scott: I'll proof read the PRs made to my repo, then PR further to the origin repo, where Razvan does the last check.

**Comment by smolinari** [comment]
@Razvan- it looks like nothing is new on the progress component (other than it being now named QProgress 😄 ). Is that correct? 

Ping @oswaldomilet - so you know I asked here about this.

Scott

**Comment by smolinari** [comment]
I'm taking stepper now.

Scott

**Comment by smolinari** [comment]
Also, @rstoenescu for your comments on the first comment above. I just noticed I mentioned you incorrectly. LOL! 😄 

Scott

**Comment by oswaldomilet** [comment]
I didn't find nothing to document in autocomplete, there are just few template/script changes, but that don't add new behaviors to component.

The only thing I found was the escape key (27) treatment, but keys are not currently documented, so I guess nothing to do with it.

**Comment by smolinari** [comment]
@oswaldomilet - Ok. I've marked off autocomplete. @rstoenescu - are we possibly missing something with the autocomplete and progress components?

Scott

**Comment by rstoenescu** [comment]
@oswaldomilet @smolinari yes. Autocomplete is wrapped by an input now, not wrapping as in 0.13. That's one change. there may be others. Look careful at code and examples, props, etc.

**Comment by smolinari** [comment]
@rstoenescu - how about the progress component. Can you roughly point to the changes there to?

Scott

**Comment by smolinari** [comment]
I'm taking on inner loading.

Scott

**Comment by smolinari** [comment]
I'm on spinner.

Scott

**Comment by smolinari** [comment]
I'm also doing observables. 

Scott

**Comment by smolinari** [comment]
And I'm doing my best with autocomplete.

Scott

**Comment by smolinari** [comment]
Taking on layout. 

Scott
