### ISSUE TITLE
There are not color set by default for the font in the android iframe

### ISSUE THREAD

**Issue by AlexandreBonneau** [quasarframework/quasar-framework.org#111]
### What did you get as the error?
While the main website does define the `font-color` on the `body` tag to `#34495e`, this not the case in the android iframe.
This leads to unreadable text if the user (like myself) changed the default `background-color` and `color` to a dark theme (which means my font `color` is very light, and since `background-color` is set, it result is a [white on white text](http://i.imgur.com/SVzNf4s.png)).

### What were you expecting?
Being able to read the text, without having to rely on the stylish extension.

### What steps did you take, to get the error?
Browser that [page](http://quasar-framework.org/components/loading.html), then try to read the text in that iframe.

**Comment by rstoenescu** [comment]
Thanks @AlexandreBonneau for issuing all the github tickets. Will fix them before the v0.14 release. Edge support for documentation wasn't on the map until now.

**Comment by AlexandreBonneau** [comment]
Ah sorry I forgot to mention that I'm using Firefox dev edition (so currently `54.0a2 (2017-04-18) (64 bits)`) under Linux.

So...no need to support Edge on my end ;P

**Comment by rstoenescu** [comment]
Should work for the beta now (http://beta.quasar-framework.org/)
