### ISSUE TITLE
Wrong `z-index` on the Card with Map example

### ISSUE THREAD

**Issue by AlexandreBonneau** [quasarframework/quasar-framework.org#112]
### What did you get as the error?
On that [cards with map](http://quasar-framework.org/components/cards.html#Card-with-Map) example, the 'Have a drink' background color is in front of the `'+'` button, as you can see [here](http://i.imgur.com/5TyJesZ.png).

### What were you expecting?
It's `z-index` should be lower that the button one.

### What steps did you take, to get the error?
Browse the [cards with map](http://quasar-framework.org/components/cards.html#Card-with-Map) page.

**Comment by AlexandreBonneau** [comment]
This is still the case under Firefox 55.0b3.

Was that behavior expected?

**Comment by rstoenescu** [comment]
Sorry for not mentioning the full story.
Closed it because on beta (v0.14 - http://beta.quasar-framework.org/) it's now obsolete. Beta will become stable in a few weeks and replace current v0.13.

**Comment by AlexandreBonneau** [comment]
Good then ;)
