### ISSUE TITLE
Selecting a date does not update the date

### ISSUE THREAD

**Issue by AlexandreBonneau** [quasarframework/quasar-framework.org#113]
### What did you get as the error?
Browsing this [example page](http://quasar-framework.org/components/list.html#List-with-Form-Components), if you scroll to 'Date and Time', then try to change the date using the component, once you've clicked on the day number (ie. '10'), the date is updated in date picker, but the date picker is not closed automatically and the input field still show the previous date if you click elsewhere.

### What were you expecting?
Clicking on the day number should close the date picker and update the input field.

**Comment by rstoenescu** [comment]
Fixed on v0.14 beta website.
