### ISSUE TITLE
Vertical slider

### ISSUE THREAD

**Issue by jersobh** [quasarframework/quasar-framework.org#129]
Hi folks

I'm trying to create a vertical slider, but with the style="-webkit-appearance: slider-vertical", or  -webkit-transform: rotate(-90.0deg); or -webkit-transform: rotate(270deg);, even though it's vertical, you can only change the value by sliding it left/right (not up/down)

**Comment by smolinari** [comment]
Hi,

In general, we'd rather have only issues and suggestions in the repos. So, please use either the [forum](http://forum.quasar-framework.org/) or the [gitter channel](https://gitter.im/quasarframework/Lobby) for such questions. You'll get answers there for sure. Please just have some patience. 

Thanks. 😄 

Scott
