### ISSUE TITLE
Handler for @input on <q-datetime-range> doesn't get executed

### ISSUE THREAD

**Issue by amaranthius** [quasarframework/quasar-framework.org#146]
Steps to reproduce:
1.   Setup a Datetime Range component, like so:
```
<q-datetime-range class="full-width"
        type="date"
        v-model="dateRange"
        :min="dateRange.min"
        @input="onRangeChange">
</q-datetime-range>

```
where `onRangeChange` can be as simple as `alert('something')`.

2.   Try selecting different values

Expected result: Each time `alert('something')` is executed
Actual result: Nothing happens

Notes:

- I can see the event is being emitted, using Vue Devtools in Chrome

- This works correctly for `<q-datetime>`, with the exact same setup

### Software version

Quasar: 0.13.10
Browsers: Chrome 58.0.3029

**Comment by rstoenescu** [comment]
This is not a documentation bug. Can you open this one on Quasar's main repo pls? https://github.com/quasarframework/quasar/issues

**Comment by amaranthius** [comment]
Apologies, didn't realize this isn't the right repo. Moved to [https://github.com/quasarframework/quasar/issues/620](https://github.com/quasarframework/quasar/issues/620)
