### ISSUE TITLE
v0.14: Document colored title for card component

### ISSUE THREAD

**Issue by a47ae** [quasarframework/quasar-framework.org#193]
In the old docs it was also documented how to color card titles by using
```
class="bg-primary text-white"
```

Currently the section [Coloring Cards](http://beta.quasar-framework.org/components/card.html#Coloring-Cards) only demonstrates how to color the whole card, but not the title.

Or the `QCardTitle` component should also accept an color prop, and this should be documented.

**Comment by rstoenescu** [comment]
Same thing applies to the new card titles too. This is using basic CSS helper classes (which apply background and text color) that obviously work on any DOM element or component (which does not has `color` prop).
