### ISSUE TITLE
Incorrect link to Pull Request Guidelines in Pull Request Placeholder Text

### ISSUE THREAD

**Issue by JCharante** [quasarframework/quasar-framework.org#198]
### Software version

Quasar: N/A
Browsers: Google Chrome Version 58.0.3029.110 (64-bit)
Any other software related to your bug: Github

### What did you get as the error?
404 Status Code

### What were you expecting?
200 Status Code & the Pull Request Guidelines

### What steps did you take, to get the error?

I went to https://github.com/quasar-framework/quasar/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines as the pull request placeholder text recommended (see below)

![image](https://user-images.githubusercontent.com/13973198/28128088-8e740e5c-66fc-11e7-8346-735fdd4fa6d4.png)

## Fix:

The link to the Pull Request Guidelines is supposed to be https://github.com/quasarframework/quasar/blob/dev/.github/CONTRIBUTING.md#pull-request-guidelines, because there is no hyphen in quasarframework.

**Comment by rstoenescu** [comment]
Hi, currently on vacation. Can you please provide a quick PR? Thank you.

**Comment by JCharante** [comment]
I didn't know `.github/PULL_REQUEST_TEMPLATE.md` existed. Created #200
