### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by johncloud200** [quasarframework/quasar-framework.org#207]
http://beta.quasar-framework.org/components/layout.html (back-to-top button)

http://beta.quasar-framework.org/components/components/back-to-top.html
should be
http://beta.quasar-framework.org/components/back-to-top.html

**Comment by rstoenescu** [comment]
Care for a quick PR pls? (hit the pencil icon at top of page or "edit" link at bottom of page; no need to clone etc; in browser PR) Thanks for reporting!

**Comment by a47ae** [comment]
Maybee we should integrate something like [check-pages](https://www.npmjs.com/package/check-pages) into the gulp process to automatically check for broken links?

**Comment by spectrolite** [comment]
from gitter today:
Robin @a47ae 18:33
Hey there I quickly ran the components section through the W3C link checker and these are the reported broken links:
back-to-top.html -> http://beta.quasar-framework.org/components/components/scroll-observable.html
button.html -> http://beta.quasar-framework.org/components/components/spinners.html
scroll-directive.html -> http://beta.quasar-framework.org/components/components/scroll-observable.html
scroll-directive.html -> http://beta.quasar-framework.org/components/utils.html
alert.html -> http://beta.quasar-framework.org/api/css-color-palette.html
stepper.html -> http://beta.quasar-framework.org/components/components/buttons.html
stepper.html -> https://en.wikipedia.org/wiki/Wizard_(software
tabs.html -> http://beta.quasar-framework.org/components/layout-overview.html
global-event-bus.html -> http://beta.quasar-framework.org/api/js-app-visibility.html
knob.html -> http://beta.quasar-framework.org/componnets/color-palette.html
toast.html -> http://beta.quasar-framework.org/api/css-icons.html
scroll-fire.html -> http://beta.quasar-framework.org/components/components/scroll-observable.html
scroll-fire.html -> http://beta.quasar-framework.org/components/utils.html
layout.html -> http://beta.quasar-framework.org/components/components/back-to-top.html
So still a lot of broken links. In @johncloud200 issue I asked to use something like the gulp check pages plugin, to automatically detect those, but I thin @rstoenescu closed it to quick

**Comment by JCharante** [comment]
@spectrolite yup, @a47ae created #209. Not sure if it's better to switch over to that issue or reopen this one.
