### ISSUE TITLE
bug: bad link in beta documentation

### ISSUE THREAD

**Issue by mattwright** [quasarframework/quasar-framework.org#219]
Sorry, I couldn't find where the repo is for the beta docs... The 'view source' link of the demo on this page:

http://beta.quasar-framework.org/components/tabs.html

points to:

https://github.com/quasarframework/quasar-play/tree/v0.14/src/components/showcase/navigation/tabs.vue

which is a 404 not found page. It should probably point to:

https://github.com/quasarframework/quasar-play/blob/v0.14/src/components/showcase/navigation/tabs/basic-tabs.vue

**Comment by rstoenescu** [comment]
Fixed. Thanks for reporting!
