### ISSUE TITLE
q-icon must be used for icon only buttons

### ISSUE THREAD

**Issue by danielo515** [quasarframework/quasar-framework.org#221]
Hello,

Documentation says that, for round buttons you need to only specify an icon as content:

> For round buttons, only use an icon as content, through “icon” property or QIcon component as the only child. Do not add anything else besides the icon, unless you want a Popover or Tooltip.

However, nothing says that, if you want a normal, small, rectangle button with an icon you must use `q-icon` as a button child. If you use the icon property, the icon appears aligned to the left, like it was leaving space for an hypothetical text. Using a `q-icon` as only child of the button fixes this problem. Take a look at the following screenshot, the button on the right uses the icon property while the one at left uses a `q-icon` child:

![captura de pantalla 2017-08-14 09 49 23](https://user-images.githubusercontent.com/2270425/29262707-07061c32-80d6-11e7-8fbe-a9696821f88a.png)

Here is the code for more concrete issue:

```html
    <q-toolbar slot="header">
      <q-btn outline @click="openTab('extract')">
        <q-icon name="menu" />
      </q-btn>
      <q-btn outline icon="alarm" @click="openTab('alarm')">
      </q-btn>

    </q-toolbar>
```

Not sure if this is a documentation issue, or just a bug. In any case, is good to notice it.

Quasar: 0.14
Browsers: Crhome

**Comment by rstoenescu** [comment]
This is by design, yes. Improved docs to be more clear. Thanks for reporting.
