### ISSUE TITLE
q-drawer is in docs but not found 

### ISSUE THREAD

**Issue by sandman18** [quasarframework/quasar-framework.org#277]
Was q-drawer removed from quasar?  It is still in the docs?  What do we use to replace it?

### Software version

Quasar:
Browsers:
Any other software related to your bug:

**Comment by JCharante** [comment]
It was removed in 0.14. You now use the `left` and `right` slots on QLayout. For an example, take a look at the default template https://github.com/quasarframework/quasar-template-default/blob/master/template/src/components/Hello.vue

**Comment by spectrolite** [comment]
this will probably hold the answers you’re looking for: http://quasar-framework.org/components/layout.html#Vue-Methods
