### ISSUE TITLE
conflicting "edit here" link

### ISSUE THREAD

**Issue by tomByrer** [quasarframework/quasar-framework.org#29]
Great that your website has a 'edit this' link at the bottom of each page.  Unfortunately it jumps to `master`, while your [contributing](http://quasar-framework.org/guide/contributing.html) rules say to fork `dev'.

Could the forking-branch links be fixed?

**Comment by rstoenescu** [comment]
Thanks for reporting this. Will get fixed.

**Comment by tomByrer** [comment]
Thanks for helping me be lazier! ;)

**Comment by rstoenescu** [comment]
:))))
