### ISSUE TITLE
Document building the front-end

### ISSUE THREAD

**Issue by MartinMuzatko** [quasarframework/quasar-framework.org#290]
Hello!

There is only one npm script to deploy using `hexo`.
The gulp file defines some tasks, but none of them are for developing the website?
What folder do I have to open in my browser to see the build result? (if `gulp` actually builds the website)

**Comment by rstoenescu** [comment]
Hi,

You just "hexo serve".
The build and deployment is hard-coded (didn't have enough time to make it dynamic) so it needs a few symlinks created. But "hexo serve" should suffice if you want to develop for the Quasar docs.

If, on the other hand, you want to edit a page, it's simpler to do that by just hitting the pencil button at the top of the respective page, or click on the "Suggest an edit" link at bottom of the page.
