### ISSUE TITLE
[Request] Clarify the linter "small differences" with the Standard mode.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-framework.org#292]
https://github.com/quasarframework/quasar-framework.org/blob/dev/source/guide/app-linter-configuration.md
It says:
> "The boilerplate created by Quasar CLI uses ESLint as the linter, and uses the Standard preset with **some small customizations**."

I'd love to know what these are!

**Comment by rstoenescu** [comment]
Hi, Take a look at `/.eslintrc.js`.
