### ISSUE TITLE
The mobile demo view in Quasar documentation is truncated

### ISSUE THREAD

**Issue by mlenormand** [quasarframework/quasar-framework.org#3]
In Quasar documentation, the mobile demo view on the right of each page is truncated on my screen (1280 \* 1024 px). I have to zoom out (90%) to reach the "View source" and "Desktop view" buttons.
This behaviour was not present a week or two ago when I discovered Quasar.

Screenshot : 
![image](https://cloud.githubusercontent.com/assets/2403897/17849540/8f5bd5b8-6859-11e6-97b5-7033ed4b52bb.png)

**Comment by rstoenescu** [comment]
I see. Will investigate and when I update the doc today for the new Quasar version I'll fix this too. Thanks for reporting!

**Comment by mlenormand** [comment]
Seems to be fixed now ! Can be closed ?

**Comment by rstoenescu** [comment]
Hmm, but I didn't do anything to it :) Will close it and then please reopen if you see it again. Thanks!

**Comment by mlenormand** [comment]
Reproduced topday with my work computer screen :

![image](https://cloud.githubusercontent.com/assets/2403897/18755804/d35f99e6-80ed-11e6-8acd-4fed84b91dbe.png)

**Comment by rstoenescu** [comment]
Again, nothing changed. This is reaaally really weird. Will investigate.

**Comment by rstoenescu** [comment]
Reopening so I won't forget.

**Comment by rstoenescu** [comment]
Applied a simple fix. Moved "View Source" and "Desktop View" buttons on top.
