### ISSUE TITLE
A prefilled (browser autofill) password field (q-input) does not trigger the floating label to move above the password dots. The dots are overlaying the label text. Chrome 64. FF is fine.

### ISSUE THREAD

**Issue by MoacirSchmidt** [quasarframework/quasar-framework.org#331]
Quasar: 0.15.0-beta.12
Browsers: Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

A prefilled (browser autofill) password field (q-input) does not trigger the floating label to move above the password dots. The dots are overlaying the label text. Chrome 64. FF is fine.

IMPORTANT: YOU HAVE TO PREVIOUSLY SAVE THE PASSWORD! This only happens when password field is auto filled (use Ctrl-Shift-Del to clear data then F5 to force auto fill!) 

See image below:
![image](https://user-images.githubusercontent.com/15182027/36067159-c284ffcc-0e9e-11e8-9788-f5feb1372aee.png)

Code:
```
<template>
<div >
  <q-field>
    <q-input v-model="form.email" type="email" float-label="E-mail ou Login"></q-input>
  </q-field>  
  <p />
  <q-field>
    <q-input v-model="form.password" type="password" float-label="Senha" ></q-input>
  </q-field>
</div>
</template>

<script type="text/javascript">
export default {
  data () {
    return {
      form: {
        email: '',
        password: ''
      }
    }
  }
}
</script>
```

**Comment by rstoenescu** [comment]
Path just pushed. Will be available in next v0.15 beta.
