### ISSUE TITLE
Buttons don't have any feedback on iOS example page.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-framework.org#342]
Two gifs, one on desktop one on iPhone.
![feb-22-2018 09-37-39](https://user-images.githubusercontent.com/3253920/36513867-12962d00-17b5-11e8-8f83-b9851f0e3386.gif)
![2018-02-22 00 41 26 0000](https://user-images.githubusercontent.com/3253920/36513871-161ccdbc-17b5-11e8-89ad-ea34c7a06c0f.GIF)

iPhone has no feedback upon clicking. It's a gif and I'm clicking on the buttons.

( just to clarify, this iPhone image is also a GIF : D )

**Comment by rstoenescu** [comment]
Fixed in 0.15.2. Thanks for reporting.
