### ISSUE TITLE
QBtn loading/loader prop

### ISSUE THREAD

**Issue by leopiccionia** [quasarframework/quasar-framework.org#355]
The documentation for QBtn refers to both `loader` and `loading` prop, but they seem to be one and the same. I think the documentation should be fixed to clarify the correct prop name.

If I remember correctly, there are four mentions to `loader` prop, and nine mentions to `loading` prop, including code and comments.

**Comment by rstoenescu** [comment]
Thanks for reporting. Update will be live today.
