### ISSUE TITLE
Layout - View Source - Page not found

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#358]
http://quasar-framework.org/components/layout.html

View Source (on phone widget)

Error 404:
https://github.com/quasarframework/quasar-play/tree/master/src/pages/showcase/layout/layout.vue

**Comment by rstoenescu** [comment]
Hi, it's been fixed already. Will be available along v0.15.2 later today or tomorrow. Thanks for reporting though!
