### ISSUE TITLE
Bug i18n of days and months in a QDateTime

### ISSUE THREAD

**Issue by ptlmspa** [quasarframework/quasar-framework.org#361]
`<q-datetime
          :day-names="['1', '2', '3', '4', '5', '6', '7']"
          :day-months="['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']"
         ........
/>`

The component keep the default values for days and months names (and not the value passed in the properties)

**Comment by rstoenescu** [comment]
Hi,

Checked it and this should have been removed. No longer necessary with Quasar i18n in place. Docs have been updated to reflect this. Doc change going live later today or tomorrow.
