### ISSUE TITLE
event bus from normal js file?

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar-framework.org#364]
How to create events that are initiated not in a vue file, but a normal js file (and subsequently listened on from vue file)?

**Comment by mesqueeb** [comment]
This is not a good place to ask, as this is the issues related to the quasar website.
I would suggest trying the Quasar Discord: https://discordapp.com/invite/5TDhbDg

Also, just to answer. You can do something like `Vue.eventBus = new Vue()` then do `Vue.eventBus.$emit()` in external js files and catch the events in your root Vue.
