### ISSUE TITLE
z-absolute - deprecated CSS class?

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#365]
http://quasar-framework.org/components/visibility.html

In CSS file only exist `z-top` and `z-max`, but this classes not described in documentation.

**Comment by rstoenescu** [comment]
Yes, you are right. Would you be so kind to provide a PR for that page? Click on "Edit" at bottom of page or the pencil on top-right. It's an in-browser process, you don't need to fork/clone to generate the PR. Thank you!

**Comment by olegvakulenko** [comment]
GitHub says:

> You need to fork this repository to propose changes.
> Sorry, you’re not able to edit this repository directly— you need to fork it and propose your changes from there instead.
> 

Is this my options forbid do this?

**Comment by rstoenescu** [comment]
Can you contact `@BenoitRanque` on Discord pls? He'll guide you through.

**Comment by rstoenescu** [comment]
Will be available in next doc update. Thank you for contributing!!
