### ISSUE TITLE
Debugging production electron app

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/quasar-framework.org#37]
https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md

**Comment by Menighin** [comment]
Hi @rstoenescu, I'm trying to setup debugging electron app with VS Code following this link you sent, but the configuration does not work. I'm trying exactly [this](https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process-vscode.md) config and I get `Unable to find Electron app at {my_directory}`.
Any help?
