### ISSUE TITLE
QItemMain - is "lines" property valid?

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#384]
http://quasar-framework.org/components/lists-and-list-items.html

In documentation:
`There are more props available, but use only these within QItemMain:`
`lines | String / Number | Number of lines the label/sublacel can span to...`

But in `JS` only uses `labelLines` or `sublabelLines`.
Is property `lines` for QItemMain deprecated?

**Comment by rstoenescu** [comment]
It's correct. Rephrased a bit to make it more explicit:
`There are more props available for QItemTile, but only use the following when QItemTile is wrapped with QItemMain:`

Notice these props apply to QItemTile since they are within QItemTile section.
