### ISSUE TITLE
Collapsible - item-separator class not found in CSS

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#386]
http://quasar-framework.org/components/collapsible.html

In documentation:
`You can add item-separator class on the list <div> element if you want separators between Collapsibles.`

In CSS files (`quasar.mat.css`) I can only find `q-item-separator`.
Is this error in documentation?

**Comment by rstoenescu** [comment]
It is indeed obsolete. Use `separator` or `inset-separator` instead. Thanks for reporting all issues!
