### ISSUE TITLE
QItem - lack of documentation

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#387]
http://quasar-framework.org/components/collapsible.html

In documentation:
`QItem components inherited properties:`

```
icon, right-icon | String | Icon to use. Either use an icon, image, avatar or letter.
-- | -- | --
image, right-image | String | URL to image to use (point to statics). Either use an icon, image, avatar or letter.
avatar, right-avatar | String | URL to avatar to use (point to statics). Either use an icon, image, avatar or letter.
letter, right-letter | String | One character String to define a letter. Either use an icon, image, avatar or letter.

```

But on:
http://quasar-framework.org/components/lists-and-list-items.html

there is not properties like `right-icon`, `right-image`, `right-avatar`, `right-letter`.

**Comment by olegvakulenko** [comment]
Sorry, but I can't find anything about `right-*` in **Lists and List Items**:
http://quasar-framework.org/components/lists-and-list-items.html
Am I looking at wrong location?

**Comment by rstoenescu** [comment]
You don't need right-* classes in QList, QItem... simply because you'll be using QItemSide (left or right) already.

**Comment by olegvakulenko** [comment]
I understand now.
I confusing with this `QItem components inherited properties`.

**Comment by rstoenescu** [comment]
Yes, improved the wording a bit.
