### ISSUE TITLE
Spinner etc Loading UI get stuck in expensive operations

### ISSUE THREAD

**Issue by leewi9** [quasarframework/quasar-framework.org#392]
### Software version

Quasar:  latest
Browsers:  Chrome latest
Any other software related to your bug: no

### What did you get as the error?

Loading UI animation get very glitchy even stuck there when encounter a expensive js operation, like CryptoJS hash method.

### What were you expecting?

A smooth animation UI

### What steps did you take, to get the error?

```
  Loading.show({message: 'hashing...', spinner: QSpinnerIos})
// expensive operation like hashing
CryptoJS.sha256(obj)  // the Spinner will stuck here when in operation.
```

**Comment by rstoenescu** [comment]
Hi,

This is to be expected. Javascript runs on a single thread. Try using a web worker for expensive operations like this one instead so you won't block main thread which deals with the UI too, or at least yield control regularly then resume your expensive operation.
