### ISSUE TITLE
documentation bug with importing styl variables in other styl files

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/quasar-framework.org#399]
Not possible to import all color variables in other styl files any more.
from the docs:
> "variables" is a Webpack alias (defined in /config/index.js)
// which points to /src/themes/quasar.variables.styl

**Docs:** http://quasar-framework.org/components/color-palette.html#Using-Stylus-Variables

When I do `@import '~variables'` it has trouble compiling on quasar dev.
**I don't think this path in `/config/index.js` still exists...**

It does work when directly pointing to the node_module like so: `@import '../../../node_modules/quasar-framework/src/css/core.variables'`

**Comment by rstoenescu** [comment]
Right. Fixed it. Will be available along Quasar v0.15.7. Thanks for pointing this out!
