### ISSUE TITLE
Problem show Modal in quasar V0.14.9

### ISSUE THREAD

**Issue by diepvv** [quasarframework/quasar-framework.org#413]
### 
When I click button and show modal in v0.14.9, Table in my project is moved a small distance. I know this problem is fixed in version 0.15.x. But my project is a complex system has been configured. Only this modal problem. How can i fixed this problem in code?
Is my code example:

Quasar: V0.14.9
Browsers: Chorme

**Comment by diepvv** [comment]
![image](https://user-images.githubusercontent.com/13696409/37264108-44d6aea2-25de-11e8-9bc5-536cdc2540a2.png)

**Comment by diepvv** [comment]
![image](https://user-images.githubusercontent.com/13696409/37264138-62187f86-25de-11e8-9dfd-7acb361cc293.png)

**Comment by a47ae** [comment]
This is the repository for Quasars documentation.
Please ask your Question on the forum/Discord or open an issue on at https://github.com/quasarframework/quasar
