### ISSUE TITLE
popups must be installed as plugins and not components

### ISSUE THREAD

**Issue by kjetilge** [quasarframework/quasar-framework.org#433]
The manual says to install Dialog like this:
```
// quasar.conf.js
framework: {  plugins: ['Dialog']}
```
but in order to get it to work I needed to do this:
```
// quasar.conf.js
plugins: [
  'Notify',
  'Dialog',
]
```

**Comment by kjetilge** [comment]
After reviewing the manual I see that I have to install popups differently for using as a method vs a component. I spent more that an hour to find out about it. Perhaps a little warning about this and an anchor close to each method would prevent this.

**Comment by rstoenescu** [comment]
Hi,

I'm sorry you lost an hour on this, but I think the docs are very clear:

![download 3](https://user-images.githubusercontent.com/4665641/37709689-ad426cd8-2d13-11e8-9b7f-59c3d969feb7.png)
![download 4](https://user-images.githubusercontent.com/4665641/37709690-ad6734f0-2d13-11e8-8530-438b164613ef.png)

Also,
![download 5](https://user-images.githubusercontent.com/4665641/37709820-1cd058b2-2d14-11e8-8251-92a291716dc7.png)

app plugin: quasar.conf > plugins
Quasar plugin: quasar.conf > framework > plugins

**Comment by kjetilge** [comment]
Yes, I was impatient, I only read about the first method, - then started to use it for everything. I won't be the last one to do this.... but now at least, this post exists 🤣
