### ISSUE TITLE
Suggestion for improvement - Documentation of integration with Cordova.

### ISSUE THREAD

**Issue by xereda** [quasarframework/quasar-framework.org#45]
Suggestion for improvement - Documentation of integration with Cordova.

Create or enhance documentation related to Apache Cordova integration. I keep a group on the Telegram that deals with the Quasar Framework. In it, a redundant issue is the lack of documentation on how to integrate Quasar with Apache Cordova. I needed also and the documentation is very sparse.

Is there any study of this possibility?

Thank you very much for your attention.

**Comment by JCharante** [comment]
This issue may have been created before this page, but for the sake of resolving it, what is missing from http://beta.quasar-framework.org/guide/cordova-wrapper.html?

**Comment by rstoenescu** [comment]
Done for 0.15
