### ISSUE TITLE
I hate checkbox in quasar!

### ISSUE THREAD

**Issue by RALMAZ** [quasarframework/quasar-framework.org#467]
### Software version

Quasar: "quasar-cli": "^0.15.14"
Browsers: Yandex 17
Any other software related to your bug: My hate, my rage, my data

### What did you get as the error?
Axios load data for this checkbox
Default = false;
After loaded = true;
Hello? Why me?
![2018-05-18_00-35-10](https://user-images.githubusercontent.com/26162860/40205118-8b80f086-5a33-11e8-84d0-ceb08143e93b.gif)

Please pardone me, but my pain is... RAAAA

**Comment by rstoenescu** [comment]
Hi, Please use Discord to try and figure out what you're doing wrong. There's a flourishing community there willing to help. Thanks.

**Comment by rstoenescu** [comment]
A jsFiddle would also help us help you.
