### ISSUE TITLE
Spin documentation not up to date

### ISSUE THREAD

**Issue by Christilut** [quasarframework/quasar-framework.org#48]
Seems the css class `.spin` was changed to `.animate-spin` but it doesn't reflect this in the documentation.
Also goes for `.blink` and theres a few other classes that arent in the docs yet (`pop`, `scale`, `fade`)

On [this page](http://quasar-framework.org/api/css-other-helper-classes.html)

**Comment by rstoenescu** [comment]
Thanks for reporting this!

**Comment by rstoenescu** [comment]
Will be available along Quasar v0.11 documentation update really soon.
