### ISSUE TITLE
correct version of docs repo?

### ISSUE THREAD

**Issue by musicformellons** [quasarframework/quasar-framework.org#489]
I wanted to make a correction to the docs but this repo is behind on the website docs..., so I can not edit?!

Edit: Ah, when I set github to master version I have correct version. So then the edit icon in the docs should link to the master version (and not to the dev version)!?

**Comment by rstoenescu** [comment]
master branch -> currently deployed website docs
dev branch -> next version of website docs

1. Only PR on dev branch
2. If you try to edit something that it's already gone or changed from dev branch, then your change is already obsolete.

**Comment by musicformellons** [comment]
Makes sense. In my particular case I wanted to address that 'no-refocus' is mentioned twice, but apparently 'no-refocus' does not need to be documented at all anymore... see `https://quasar-framework.org/components/modal.html#Vue-Properties`.
