### ISSUE TITLE
Please share a CDN link

### ISSUE THREAD

**Issue by hmzlam** [quasarframework/quasar-framework.org#499]
I was searching docs for hours to find a cdn link, but i find this statement
" The UMD starter kit will ask you some questions and will generate a simple HTML file that will show you how to use CDN to add Quasar:"

$ vue init quasarframework/quasar-starter-kit-umd <folder_name>

if i have node and such tools I will not search for a cdn link

please add a cdn link in your website.

**Comment by PHARMACIE1801** [comment]
yes it's helpful thank you

**Comment by rstoenescu** [comment]
Done. Will be visible on next doc deployment (scheduled for this Friday).
