### ISSUE TITLE
Looking for fastlane documentation

### ISSUE THREAD

**Issue by rlam3** [quasarframework/quasar-framework.org#502]
Looking for fastlane documentation in streamlining deployment process. 
Was wondering if there was docs already available for this type of cordova app.

**Comment by rstoenescu** [comment]
Are you looking for this? https://quasar-framework.org/guide/cordova-publishing-to-store.html
If this does not suffice it, look for cordova tutorials/guide/docs.

**Comment by genuinefafa** [comment]
the link stopped working...

**Comment by rstoenescu** [comment]
https://quasar.dev/quasar-cli/developing-mobile-apps/publishing-to-store
