### ISSUE TITLE
Link to ' App Handling Static Assets' is giving 404

### ISSUE THREAD

**Issue by jayudhandha** [quasarframework/quasar-framework.org#512]
Open URL: https://quasar-framework.org/components/lists-and-list-items.html

In this doc, somewhere they have written: 

> Also read about [App Handling Static Assets](https://quasar-framework.org/guide/app-handling-static-assets.html) to understand how Webpack includes assets into the bundle

The mentioned link on **App Handling Static Assets** is giving **404**.

Checked on latest docs as well as v0-15 docs.

**Comment by smolinari** [comment]
It needs to be changed to this link. 

https://quasar-framework.org/guide/app-handling-assets.html

I've made a PR. https://github.com/quasarframework/quasar-framework.org/pull/513 

Scott

**Comment by jayudhandha** [comment]
Yes, I have seen 'app-handling-assets.html' instead of 'app-handling-static-assets.html'.

Thanks!
