### ISSUE TITLE
Homogeneity : what about replacing curly quotes by straight ones ?

### ISSUE THREAD

**Issue by kevinmarrec** [quasarframework/quasar-framework.org#515]
After looking some of the repository files, I figured that both curly quotes (`‘`, `’`, `“`, `”`) and straight quotes (`'`, `"`) are used.

I personally never use curly quotes to write code or documentations, that's a choice but I think files should always use only one of these quote types (homogeneity).

I prepared a commit ready to be submitted for a PR (where curly quotes are all replaced by straight ones) if this issue seems relevant.

**Comment by rstoenescu** [comment]
Hi,

Thank you for suggesting improvements! However in this specific case I think it doesn't matter anymore, as the docs are being re-written (using Quasar this time) right after v0.17 release. So please, do not lose time on this!

Thanks for helping out. I really appreciate it!
