### ISSUE TITLE
QKnob cut off (bounding box too small) if line-width larger than default

### ISSUE THREAD

**Issue by gschintgen** [quasarframework/quasar-framework.org#562]
(Hi, I'm rather new to all of this, so please be indulgent if this issue is too minor or if it's some kind of user error. Anyway, Quasar is truly amazing; can't wait to dive deeper.)

### Software version
Quasar CLI........ v0.17.3
Quasar Framework.. v0.17.2
Browser: Firefox 61.0.1

### What did you get as the error?
No error, but a misrendering: if the line-width of a QKnob is increased, the circular "track" is clipped at the top, bottom, left and right.
![qknob-clipped](https://user-images.githubusercontent.com/11065156/43765986-9de01eee-9a31-11e8-967d-566947189e26.png)

### What were you expecting?
I expected the bounding box of the knob to be adjusted to the new line-width.

### What steps did you take, to get the error?
```
<template>
  <q-knob
    v-model="temperature"
    readonly
    :min="12"
    :max="34"
    size="70px"
    line-width="10px"
    :color="gaugecolor"
   >
      {{ temperature }} °C
  </q-knob>
</template>
```

**Comment by rstoenescu** [comment]
Hi,

Please use a lower line-width value. QKnob cannot currently accommodate to big line-width. Sorry for any inconvenience.
