### ISSUE TITLE
Layout example - horizontal scroll

### ISSUE THREAD

**Issue by olegvakulenko** [quasarframework/quasar-framework.org#572]
On Android exist horizontal scroll (one or two pixels). This scroll only seen with Chrome, on Firefox scroll not exist.
On iPhone layout doesn't fit at all.
In documentation for v.0.16 all layouts looks normal.
I doubt that this is a bug, but it look strange.

v0.17:
https://quasar-framework.org/components/layout.html

![v17-1](https://user-images.githubusercontent.com/30389307/44242530-df846500-a1d2-11e8-868d-e11b9db097f7.png)
![v17-2](https://user-images.githubusercontent.com/30389307/44242531-df846500-a1d2-11e8-9286-b5e54a40e5de.png)

v0.16
https://v0-16.quasar-framework.org/components/layout.html

![v16-1](https://user-images.githubusercontent.com/30389307/44242174-f4f88f80-a1d0-11e8-83d7-d3620828eb24.png)
![v16-2](https://user-images.githubusercontent.com/30389307/44242175-f4f88f80-a1d0-11e8-9ac8-8d51cbe83a4b.png)

**Comment by rstoenescu** [comment]
Hi,

Can you please redirect this bug to the doc website? Thank you.
https://github.com/quasarframework/quasar-framework.org/issues
