### ISSUE TITLE
Meta plugin - description and keywords dynamic

### ISSUE THREAD

**Issue by lucassbgomes** [quasarframework/quasar-framework.org#599]
Hi!
I am using version 0.17.15, I am trying to use the meta plugin dynamically, with the title worked, but with the meta description and keywords does not load the data of the variable, I followed the example: https://github.com/quasarframework/quasar-framework.org/blob/dev/source/components/meta-plugin.md

I tried this way:
`meta () {`
`     return {`
`           title: this.titleSite,`
`meta: {`
`description: { name: 'description', content: this.descriptionSite }`
`},`
`...`
`}`

Where this.titleSite and this.descriptionSite comes from a mixin, someone can help?

**Comment by rstoenescu** [comment]
Hi,

Can you open this ticket on the Quasar main repo pls? https://github.com/quasarframework/quasar/issues

Thank you.
