### ISSUE TITLE
Documentation needs to be updated for q-search component

### ISSUE THREAD

**Issue by toymachiner62** [quasarframework/quasar-framework.org#628]
The q-search component documentation has a `suffix` attribute which the docs say is a string.

Through this thread on the forum https://forum.quasar-framework.org/topic/2853/set-q-search-suffix-attribute-dynamically/7, I see I am able to use a function such as: `:suffix="numberOfResults()"`

Documentation https://quasar-framework.org/components/search.html

I wasn't sure the best way to propose a documentation change to follow your convention so i created this issue instead

**Comment by rstoenescu** [comment]
Hello,

The result of calling "numberOfResults()" is probably a String, otherwise it wouldn't work. Suffix gets attributed a String value :)

If things are unclear for you, I recommend you take a look at https://vuejs.org/v2/guide/syntax.html
