### ISSUE TITLE
Firefox Flash of unstyled content

### ISSUE THREAD

**Issue by gleba** [quasarframework/quasar-framework.org#655]
- https://www.mozilla.org/en-US/firefox/
- macosx 10.13
![pysiz](https://user-images.githubusercontent.com/1052840/50953160-97d4e180-14c3-11e9-84bf-11daf23fcdaf.gif)

**Comment by rstoenescu** [comment]
Thanks for submitting this -- and the screen capture is awesome.

Fortunately, the docs pages for v1.0 are being rewritten from scratch, this time actually using Quasar (with SSR) to power up the website. So the current 0.17 website is already obsolete. Investigating this odd behaviour would only delay 1.0 release. Will close this, sorry for any inconvenience. As time allows after 1.0 is out, we'll investigate this too.
