### ISSUE TITLE
How to set color for dates and multi selection in DatePicker inline component

### ISSUE THREAD

**Issue by hatavan83** [quasarframework/quasar-framework.org#66]
I want to set color for dates or date range when initialize the calendar (ex: 1-1-2017 is red, 21-1-2017 is blue) and multi selection dates on calendar. Could you please guide me how to config or implement them ??

**Comment by rstoenescu** [comment]
Hi. Please use forum for questions and Quasar's main repo for bug reporting / feature request. Thanks!
