### ISSUE TITLE
Reorder the component list on the components page

### ISSUE THREAD

**Issue by smolinari** [quasarframework/quasar-framework.org#92]
I'd like to reorder the components, so they follow this ["component based design" concept](https://medium.com/@lewisplushumphreys/how-were-using-component-based-design-5f9e3176babb), The goal is to make the categorization and finding of components a bit easier. 

Any other suggestions for this improvement are highly welcomed.

Scott

**Comment by rstoenescu** [comment]
Components
===

- [ ] Introduction: $
- [ ] Platform Detection: $
- [ ] Global Event Bus: js-$

Style & Identity:
  - [ ] Color Palette: css-$
  - [ ] Stylus Variables: css-$
  - [ ] Icons: $
  - [ ] Material Ripples: $
  - [ ] Typography: css-$
  - [ ] Addressbar Color: $

Design Helpers:
  - [ ] Flex CSS: css-$
  - [ ] Shadows: css-$
  - [ ] Visibility: css-$
  - [ ] Positioning: css-$
  - [ ] Other Classes: css-$

Layout and Structure:
  - [ ] Introduction: $
  - [ ] Layout: $
  - [ ] Fixed Positioning on Layout: $
  - [ ] Element Resize Observable: $
  - [ ] Window Resize Observable: $
  - [ ] Relocating Nodes: $

Navigation:
  - [ ] Toolbar: $
  - [ ] Tab: $
  - [ ] Pull to refresh: $
  - [ ] Layout Side Links: $
  - [ ] Go Back Directive: $
  - [ ] Context Menu: $
  - [ ] Breadcrumb: $

Scrolling:
  - [ ] InfiniteScroll: $
  - [ ] Scroll Area: $
  - [ ] Scroll Fire: $
  - [ ] Scroll Observable: $
  - [ ] Back to Top: $

Animation:
  - [ ] Transition: $
  - [ ] SlideTransition: $

Touch Actions:
  - [ ] Panning: $
  - [ ] Swiping: $
  - [ ] Touch Hold: $

Popups:
  - [ ] Action Sheet: $
  - [ ] Alert: $
  - [ ] Dialog: $
  - [ ] Toast: $
  - [ ] Modal: $
  - [ ] Popover: $
  - [ ] Tooltip: $
  - [ ] Fab: $

Grouping:
  - [ ] Card: $
  - [ ] Collapsible: $
  - [ ] DataTable: $
  - [ ] HTML Table: $
  - [ ] QItem: $
  - [ ] Slider: $
  - [ ] Stepper: $

Progress:
  - [ ] Ajax Bar: $
  - [ ] Buttons with Progress: $
  - [ ] Loading: $
  - [ ] Inner Loading: $
  - [ ] Linear Progress: $
  - [ ] Circular Progress (Spinner): $

Forms:
  - [ ] Buttons: $
  - [ ] Field: $
  - [ ] Input: $
  - [ ] ChipsInput: $
  - [ ] Autocomplete: $
  - [ ] Search: $
  - [ ] Range: $
  - [ ] DoubleRange: $
  - [ ] Radio: $
  - [ ] Checkbox: $
  - [ ] Toggle: $
  - [ ] OptionGroup: $
  - [ ] Datetime: $
  - [ ] InlineDatetime: $
  - [ ] DatetimeRange: $
  - [ ] Pagination: $
  - [ ] Select: $
  - [ ] DialogSelect: $
  - [ ] Rating: $
  - [ ] Knob: $
  - [ ] Uploader: $

Media:
  - [ ] ImageGallery: $
  - [ ] Parallax: $
  - [ ] Video Embedding: $

Miscellaneous:
  - [ ] Chat: $
  - [ ] Tree: $
  - [ ] Utils: js-$

Web API Wrappers:
  - [ ] Cookies: js-$
  - [ ] Web Storage: js-$
  - [ ] App Visibility: js-$
  - [ ] App Fullscreen: js-$

**Comment by smolinari** [comment]
That looks awesome! 😉 I agree, the original intention doesn't do the right job in terms of division. This is much better!

Scott

**Comment by smolinari** [comment]
I've done a recheck and correction of button. Input can be checked off too. 

Scott

**Comment by rstoenescu** [comment]
Reorder complete. Closing issue.
